In [61]:
import numpy as np
import pandas as pd

In [62]:
df = pd.read_csv('cards_data.csv',dtype={'has_chip':'category','card_brand':'category','card_type':'category','card_on_dark_web': 'category'})
df.head(6)

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No
5,4537,1746,Visa,Credit,4404898874682993,09/2003,736,YES,1,$27500,09/2003,2012,No

In [63]:
df['card_brand'].values.categories

Index(['Amex', 'Discover', 'Mastercard', 'Visa'], dtype='object')

In [64]:
df['card_type'].values.categories

Index(['Credit', 'Debit', 'Debit (Prepaid)'], dtype='object')

In [65]:
df['has_chip'].values.categories

Index(['NO', 'YES'], dtype='object')

In [66]:
df['card_on_dark_web'].values.categories

Index(['No'], dtype='object')

In [67]:
df['acct_open_date'] = pd.to_datetime(df['acct_open_date'], format='%m/%Y')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   category
 3   card_type              6146 non-null   category
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   object
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   category
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   object
 10  acct_open_date         6146 non-null   datetime64[ns]
 11  year_pin_last_changed  6146 non-null   int64
 12  card_on_dark_web       6146 non-null   category
dtypes: category(4), datetime64[ns](1), int64(6), object(2)
memory usage: 456.7+ KB

In [69]:
df['expires'] = pd.to_datetime(df['expires'], format='%m/%Y')

In [70]:
df['credit_limit'] = df['credit_limit'].str.replace('$', '', regex=False).astype(int)

In [71]:
# Now check all the data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   category
 3   card_type              6146 non-null   category
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   datetime64[ns]
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   category
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   int64
 10  acct_open_date         6146 non-null   datetime64[ns]
 11  year_pin_last_changed  6146 non-null   int64
 12  card_on_dark_web       6146 non-null   category
dtypes: category(4), datetime64[ns](2), int64(7)
memory usage: 456.7 KB

In [72]:
df.loc[df.isna().any(axis=1)] # no missing values

Empty DataFrame
Columns: [id, client_id, card_brand, card_type, card_number, expires, cvv, has_chip, num_cards_issued, credit_limit, acct_open_date, year_pin_last_changed, card_on_dark_web]
Index: []

In [73]:
df.loc[df['cvv'] <100]

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,2009-03-01,75,YES,1,28,2008-09-01,2009,No
7,3687,1746,Mastercard,Debit,5627220683410948,2022-06-01,48,YES,2,9022,2003-07-01,2015,No
17,5621,708,Visa,Debit,4032240655674503,2022-06-01,53,YES,1,132439,2010-11-01,2011,No
20,27,68,Visa,Credit,4099623033306950,2021-09-01,74,YES,2,9900,2002-01-01,2019,No
37,138,1094,Visa,Debit,4556928160477229,2023-06-01,64,YES,2,2365,2007-01-01,2009,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6071,171,7,Mastercard,Debit,5673440794177682,2023-04-01,44,NO,2,21274,2008-01-01,2009,No
6085,2546,1805,Mastercard,Credit,5541745788882180,2022-02-01,58,NO,1,3800,2007-04-01,2007,No
6098,3752,1528,Visa,Credit,4784666596890935,2022-02-01,50,YES,2,7700,2005-07-01,2015,No
6127,3488,391,Mastercard,Debit,5021628982108623,2024-08-01,87,YES,1,11812,2010-06-01,2010,No
6132,1765,588,Mastercard,Debit,5800888888822204,2020-02-01,80,YES,1,26265,2020-02-01,2020,No

In [74]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, client_id, card_brand, card_type, card_number, expires, cvv, has_chip, num_cards_issued, credit_limit, acct_open_date, year_pin_last_changed, card_on_dark_web]
Index: []

In [75]:
df.to_csv("cards_data_cleaned.csv", index=False)