In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('transactions_data.csv',dtype={'use_chip':'category','merchant_city':'category','merchant_state':'category','errors': 'category'})

In [3]:
df['date'] = pd.to_datetime(df['date'])

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13305915 entries, 0 to 13305914
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   id              int64
 1   date            datetime64[ns]
 2   client_id       int64
 3   card_id         int64
 4   amount          object
 5   use_chip        category
 6   merchant_id     int64
 7   merchant_city   category
 8   merchant_state  category
 9   zip             float64
 10  mcc             int64
 11  errors          category
dtypes: category(4), datetime64[ns](1), float64(1), int64(5), object(1)
memory usage: 888.6+ MB

In [5]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, date, client_id, card_id, amount, use_chip, merchant_id, merchant_city, merchant_state, zip, mcc, errors]
Index: []

In [6]:
df.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,$80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,$200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,$46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN

In [7]:
df['amount'] = df['amount'].str.replace('$', '', regex=False).astype(float)

In [8]:
df.loc[df['errors'].notna()]

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
166,7475516,2010-01-01 04:56:00,464,3233,104.10,Swipe Transaction,32175,Orlando,FL,32804.0,7538,Technical Glitch
248,7475611,2010-01-01 06:10:00,1797,1127,28.84,Online Transaction,15143,ONLINE,NaN,NaN,4784,Bad Expiration
275,7475643,2010-01-01 06:19:00,1797,1127,38.58,Online Transaction,15143,ONLINE,NaN,NaN,4784,Bad Card Number
401,7475792,2010-01-01 07:02:00,1424,4710,-72.00,Swipe Transaction,59935,Kingman,AZ,86401.0,5499,Insufficient Balance
483,7475881,2010-01-01 07:22:00,843,184,37.54,Swipe Transaction,89462,Terre Haute,IN,47805.0,5300,Insufficient Balance
...,...,...,...,...,...,...,...,...,...,...,...,...
13305422,23761252,2019-10-31 19:13:00,1902,3056,99.28,Chip Transaction,61677,Caldwell,OH,43724.0,5411,Technical Glitch
13305606,23761496,2019-10-31 20:48:00,1985,4085,10.74,Chip Transaction,70635,Alpharetta,GA,30022.0,5310,Bad PIN
13305757,23761675,2019-10-31 21:57:00,87,3607,20.00,Chip Transaction,27092,Leander,TX,78641.0,4829,Insufficient Balance
13305803,23761735,2019-10-31 22:23:00,1851,3164,166.38,Online Transaction,32480,ONLINE,NaN,NaN,4899,Insufficient Balance
13305894,23761849,2019-10-31 23:39:00,348,3073,61.67,Chip Transaction,60569,Hampton,NJ,8827.0,5300,Insufficient Balance

In [9]:
df.loc[df.drop(columns=['errors','merchant_state']).isna().any(axis=1) & (df['merchant_city'] != 'ONLINE')]

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
581,7476010,2010-01-01 07:53:00,1579,3830,6.51,Swipe Transaction,22204,Puerto Vallarta,Mexico,NaN,5541,NaN
1026,7476549,2010-01-01 10:03:00,363,5555,8.16,Swipe Transaction,93391,Vatican City,Vatican City,NaN,5812,NaN
1148,7476704,2010-01-01 10:37:00,363,5555,11.66,Swipe Transaction,93391,Vatican City,Vatican City,NaN,5812,NaN
1706,7477375,2010-01-01 12:50:00,1266,2478,9.77,Swipe Transaction,22204,Guadalajara,Mexico,NaN,5541,NaN
1836,7477534,2010-01-01 13:19:00,1266,2478,11.32,Swipe Transaction,75804,Guadalajara,Mexico,NaN,5411,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
13304162,23759669,2019-10-31 13:16:00,905,53,18.97,Swipe Transaction,46284,Prague,Czech Republic,NaN,5411,NaN
13304376,23759927,2019-10-31 14:03:00,905,5053,171.95,Swipe Transaction,51300,Prague,Czech Republic,NaN,3359,NaN
13304475,23760060,2019-10-31 14:28:00,905,5053,-377.00,Chip Transaction,51300,Prague,Czech Republic,NaN,3359,NaN
13305061,23760796,2019-10-31 16:45:00,738,5774,317.42,Swipe Transaction,16790,Paris,France,NaN,3389,NaN
13305140,23760892,2019-10-31 16:58:00,738,5774,-494.00,Swipe Transaction,16790,Paris,France,NaN,3389,NaN

In [10]:
df['merchant_city'].values.categories

Index(['Abbeville', 'Aberdeen', 'Abilene', 'Abingdon', 'Abita Springs',
       'Absecon', 'Abu Dhabi', 'Accokeek', 'Acworth', 'Adams',
       ...
       'Virginia City', 'Weatogue', 'Chester Heights', 'Dalton City',
       'East Point', 'Eastville', 'El Rito', 'Maidens', 'King Ferry',
       'Shawboro'],
      dtype='object', length=12492)

In [11]:
df['merchant_state'].values.categories

Index(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'Canada', 'China',
       'Costa Rica',
       ...
       'Albania', 'Guinea', 'Papua New Guinea', 'East Timor (Timor-Leste)',
       'Sudan', 'Venezuela', 'Trinidad and Tobago', 'Republic of the Congo',
       'Azerbaijan', 'Guyana'],
      dtype='object', length=199)

In [12]:
df['use_chip'].values.categories

Index(['Online Transaction', 'Swipe Transaction', 'Chip Transaction'], dtype='object')

In [13]:
df['errors'].values.categories

Index(['Bad CVV', 'Bad Card Number', 'Bad Card Number,Bad Expiration',
       'Bad Card Number,Insufficient Balance', 'Bad Expiration',
       'Bad Expiration,Technical Glitch', 'Bad PIN',
       'Bad PIN,Insufficient Balance', 'Bad PIN,Technical Glitch',
       'Bad Zipcode', 'Insufficient Balance',
       'Insufficient Balance,Technical Glitch', 'Technical Glitch',
       'Bad Card Number,Bad CVV', 'Bad Expiration,Insufficient Balance',
       'Bad CVV,Technical Glitch', 'Bad Expiration,Bad CVV',
       'Bad CVV,Insufficient Balance', 'Bad Card Number,Technical Glitch',
       'Bad Zipcode,Insufficient Balance',
       'Bad Card Number,Bad Expiration,Insufficient Balance',
       'Bad Zipcode,Technical Glitch'],
      dtype='object')

In [16]:
df.head(10)

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN
5,7475333,2010-01-01 00:07:00,1807,165,4.81,Swipe Transaction,20519,Bronx,NY,10464.0,5942,NaN
6,7475334,2010-01-01 00:09:00,1556,2972,77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
7,7475335,2010-01-01 00:14:00,1684,2140,26.46,Online Transaction,39021,ONLINE,NaN,NaN,4784,NaN
8,7475336,2010-01-01 00:21:00,335,5131,261.58,Online Transaction,50292,ONLINE,NaN,NaN,7801,NaN
9,7475337,2010-01-01 00:21:00,351,1112,10.74,Swipe Transaction,3864,Flushing,NY,11355.0,5813,NaN

In [15]:
df.to_csv("transactions_data_cleaned.csv", index=False)

KeyboardInterrupt: